// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:pet_diary/hive/hive_adapters.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AppointmentTypeAdapter());
    registerAdapter(CatAdapter());
    registerAdapter(DiaryEntryAdapter());
    registerAdapter(EntryTypeAdapter());
    registerAdapter(FishAdapter());
    registerAdapter(PetAppointmentAdapter());
    registerAdapter(PetTypeAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(AppointmentTypeAdapter());
    registerAdapter(CatAdapter());
    registerAdapter(DiaryEntryAdapter());
    registerAdapter(EntryTypeAdapter());
    registerAdapter(FishAdapter());
    registerAdapter(PetAppointmentAdapter());
    registerAdapter(PetTypeAdapter());
  }
}
